id: PAD84D6A2
initial_creation_type: input
source_metadata:
  Title: Laghukaumudīvyākaraṇam
  Editor: James R. Ballantyne
  Publisher: Motilal Banarsidass
  Place of Publication: Delhi, India
  Year: 1976 [reprint]
  Laghukaumudīvyākaraṇam:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2020'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:25:16.460797'
last_modified_at: '2022-03-08T17:25:16.460810'
